apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlas-api-credentials
  namespace: atlas-alerts
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: atlas-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_ATLAS_PUBLIC_API_KEY
      remoteRef:
        key: atlas-alerts/credentials
        property: public_key
    - secretKey: MONGODB_ATLAS_PRIVATE_API_KEY
      remoteRef:
        key: atlas-alerts/credentials
        property: private_key
    - secretKey: MONGODB_ATLAS_PROJECT_ID
      remoteRef:
        key: atlas-alerts/credentials
        property: project_id
